set(CPACK_PACKAGE_NAME "nil-xalt-dev")
set(CPACK_PACKAGE_CONTACT "njaldea@gmail.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Neil Aldea <njaldea@gmail.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "collection of utility functionalities")
include(CPack)